In [1]:
#Write a Python program to demonstrate basic operations on single array and multiple arrays
#How to Create Multi-Dimensional Arrays Using NumPy
import numpy as np
import array as arr

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Create a 2-dimensional array with 3 rows and 4 columns
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [6]:
# Print the array
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
a=np.array([['Sanika','Komal','Rutuja'],['Pragati','sonal','shweta'],['Dhanu','poonam','Tajal']])
print(a)

[['Sanika' 'Komal' 'Rutuja']
 ['Pragati' 'sonal' 'shweta']
 ['Dhanu' 'poonam' 'Tajal']]


In [8]:
# Create a 2-dimensional array with 3 rows and 4 columns
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
# Access an element at row 1, column 2
print(b[1, 2])

7


In [10]:
# Modify an element at row 0, column 3
b[0, 3] = 20

In [11]:

# Print the modified array
print(b)

[[ 1  2  3 20]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
# Calculate the sum of all elements
print(np.sum(arr))

78


In [14]:
# Calculate the mean of each row
print(np.mean(arr, axis=1))  

[ 2.5  6.5 10.5]


In [17]:
# Calculate the dot product of two matrices
b = np.array([[2, 3], [4, 5], [6, 7], [8, 9]])
print(np.dot(arr, b))  

[[ 60  70]
 [140 166]
 [220 262]]
